version: '3.7'

services:
  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - static_volume:/app/static
    env_file:
      - ./.env.cdse.prod
volumes:
  static_volume: