#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $SQL_USER_DJANGO WITH PASSWORD '$SQL_PASSWORD_DJANGO';
  CREATE DATABASE $SQL_DATABASE_DJANGO;
  GRANT ALL PRIVILEGES ON DATABASE $SQL_DATABASE_DJANGO TO $SQL_USER_DJANGO;

  CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
  CREATE DATABASE $DB_DATABASE;
  GRANT ALL PRIVILEGES ON DATABASE $DB_DATABASE TO $DB_USER;
EOSQL