# Generated by Django 3.2.6 on 2021-08-09 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("predictionmodel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionmodelsession",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PredictionModelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system", models.CharField(max_length=2048)),
                ("code", models.CharField(max_length=64)),
                (
                    "child",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictionmodel.predictionmodeldata",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="predictionmodelsession",
            name="session_input",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="predictionmodel.predictionmodeldata",
            ),
        ),
    ]
