# Generated by Django 3.2.6 on 2021-08-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("predictionmodel", "0003_predictionmodeldata_input_parameter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionmodelsession",
            name="session_input",
        ),
        migrations.AddField(
            model_name="predictionmodeldata",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="predictionmodel.predictionmodelsession",
            ),
        ),
    ]
