# Generated by Django 3.2.6 on 2021-08-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predictionmodel", "0004_auto_20210809_1529"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictionmodeldata",
            old_name="child",
            new_name="child_parameter",
        ),
    ]
