# Generated by Django 3.2.6 on 2021-08-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictionmodel", "0007_auto_20210811_1345"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionmodelsession",
            name="image_id",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="predictionmodelsession",
            name="image_name",
            field=models.CharField(default="", max_length=2048),
            preserve_default=False,
        ),
    ]
