# Generated by Django 3.2.6 on 2021-08-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictionmodel", "0008_auto_20210811_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionmodelsession",
            name="model_uri",
            field=models.CharField(default="", max_length=2048),
            preserve_default=False,
        ),
    ]
