# Generated by Django 3.2.6 on 2021-08-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("predictionmodel", "0009_predictionmodelsession_model_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionmodelresult",
            name="child_parameter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="predictionmodel.predictionmodelresult",
            ),
        ),
    ]
