# Generated by Django 3.2.6 on 2021-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictionmodel", "0010_predictionmodelresult_child_parameter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionmodelresult",
            name="calculated_value",
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
