# Generated by Django 3.2.6 on 2021-08-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predictionmodel", "0011_alter_predictionmodelresult_calculated_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictionmodelresult",
            old_name="child_parameter",
            new_name="parent_parameter",
        ),
    ]
