# Generated by Django 3.2.6 on 2021-08-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictionmodel", "0013_predictionmodelsession_calculation_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionmodelsession",
            name="error",
            field=models.TextField(default=None, null=True),
        ),
    ]
